### PR TITLE
Update autoconsent to 4.1.1, drop Node 12

### PR DESCRIPTION
**Pull request by muodov**
**Breaking change**: Node 12 is not supported anymore because puppeteer dropped support last year

### CODE REVIEW

**Comment by muodov** [comment]
@kdzwinel looking at the test failure, could it be related to https://github.com/duckduckgo/privacy-test-pages/pull/114 ?

**Comment by kdzwinel** [comment]
Per our discussion about keeping 10.2 - we don't want to merge this branch, right? At least not with pptr update?

**Comment by muodov** [comment]
@kdzwinel yep, I've removed the puppeteer upgrade.
In case there's someone watching these changes, it seems like our current usage of raw CDP is incompatible with the latest puppeteer. You can still use `--chromium-version` to run the tracker-radar-collector with a newer browser version

**Review by kdzwinel — APPROVED** [review]
LGTM, thanks Max!

**Pull request merged**
